CREATE TABLE IF NOT EXISTS TB_CLIENTES
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT ,
    NOME      VARCHAR(200) NOT NULL ,
    DOCUMENTO INTEGER      NOT NULL ,
    PLANOID   VARCHAR(10)  NOT NULL ,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT
  INTO TB_CLIENTES (NOME ,DOCUMENTO ,PLANOID)
VALUES ('Jose Almeida' ,53214 ,1);
INSERT
  INTO TB_CLIENTES (NOME ,DOCUMENTO ,PLANOID)
VALUES ('Maria Rita' ,65474 ,1);
INSERT
  INTO TB_CLIENTES (NOME ,DOCUMENTO ,PLANOID)
VALUES ('Joao da Silva' ,32165 ,2);
INSERT
  INTO TB_CLIENTES (NOME ,DOCUMENTO ,PLANOID)
VALUES ('Mariana Menezes' ,98532 ,2);
INSERT
  INTO TB_CLIENTES (NOME ,DOCUMENTO ,PLANOID)
VALUES ('Rita de Cassia' ,54512 ,3);
