CREATE TABLE IF NOT EXISTS TB_CLIENTES
(
    ID        INTEGER      NOT NULL ,
    NOME      VARCHAR(200) NOT NULL ,
    DOCUMENTO INTEGER      NOT NULL ,
    PLANO     INTEGER ,
    PRIMARY KEY (ID)
);

INSERT INTO TB_CLIENTES (ID, NOME ,DOCUMENTO ,PLANO) VALUES (1, 'Jose Almeida' ,532 ,1);
INSERT INTO TB_CLIENTES (ID, NOME ,DOCUMENTO ,PLANO) VALUES (2, 'Maria Rita' ,653 ,1);
INSERT INTO TB_CLIENTES (ID, NOME ,DOCUMENTO ,PLANO) VALUES (3, 'Joao da Silva' ,321 ,2);
INSERT INTO TB_CLIENTES (ID, NOME ,DOCUMENTO ,PLANO) VALUES (4, 'Mariana Menezes' ,985 ,2);
INSERT INTO TB_CLIENTES (ID, NOME ,DOCUMENTO ,PLANO) VALUES (5, 'Rita de Cassia' ,545 ,0);
