CREATE TABLE IF NOT EXISTS TB_PLANO
(
    ID        INTEGER       NOT NULL ,
    NOME      VARCHAR(200) NOT NULL ,
    PRIMARY KEY (ID)
);

INSERT
  INTO TB_PLANO (ID, NOME )
VALUES (1, 'Bronze');
INSERT
  INTO TB_PLANO (ID, NOME)
VALUES (2, 'Prata');
INSERT
  INTO TB_PLANO (ID, NOME)
VALUES (3, 'Ouro');
